### ISSUE TITLE
Why does the jar contain snake-yaml?

### ISSUE THREAD

**Issue by trevershick** [DiUS/java-faker#130]
Generally speaking, the main artifact for a library should NOT include dependencies.  This can cause issues in larger projects where the shaded classes may cause duplicate classes.

A better option is to publish an unshaded jar by default and add another jar identified by a classifier like 'deps'.

It's a little odd because this shaded jar ONLY contains the snake-yaml dependency and nothing else, yet there are plenty of other dependencies.

Would you guys be open to publishing the shaded jar with a <classifier>deps</classifier> ?

**Comment by trevershick** [comment]
Does anyone have an issue with me changing the Pom to publish a deps jar and a non deps jar?

**Comment by codingricky** [comment]
That's fine.

**Comment by PascalSchumacher** [comment]
@trevershick I requested the shading, because the sake-yaml fork used by java-faker is not in maven central or any other "well known" repository. So companies with strict policies concerning allowed maven repositories can not use it.

I should have enabled the package name rewrite feature of the shade plugin to prevent the potential dependency conflict. Sorry about that.

**Comment by codingricky** [comment]
@pascalschumacher publishing 2 jar files should solve that problem no?

**Comment by PascalSchumacher** [comment]
Yes the problem remains solved. I just wanted to add some context.

**Comment by codingricky** [comment]
Cool awesome :)

**Comment by trevershick** [comment]
Thanks for the info @pascalschumacher
